FROM php:8.3-alpine

############# Setup dependencies #############

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN apk update \
    && apk upgrade \
    && apk add \
    curl \
    zip \
    && install-php-extensions bcmath exif intl gd pdo_mysql \
    && apk cache clean

############# Setup working directory #############

RUN mkdir -p /app

WORKDIR /app

############# Setup entrypoint #############

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENV PHP_CLI_SERVER_WORKERS=10

ENTRYPOINT [ "entrypoint.sh" ]

CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=80" ]
