FROM node:22-alpine

############# Setup dependencies #############

RUN apk update \
    && apk upgrade \
    && apk cache clean

############# Setup working directory #############

RUN mkdir -p /app

WORKDIR /app

############# Setup entrypoint #############

COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "entrypoint.sh" ]

CMD [ "npm", "run", "dev" ]
